language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=Wikiwide
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse

after_success:
    if [[ $TRAVIS_TAG ]]; then python -m pip install twine; python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl; else for wheel in wheelhouse/*.whl; do curl -F "file=@$wheel" https://file.io/?expires=1d; done; fi

deploy:
  provider: releases
  api_key: ${GITHUB}
  file_glob: true
  file: wheelhouse/*.whl
  skip_cleanup: true
