language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=Wikiwide
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse

after_success:
    if [[ $TRAVIS_TAG ]]; then python -m pip install twine; python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl; else for wheel in wheelhouse/*.whl; do curl -F "file=@$wheel" https://file.io/?expires=1d; done; fi


before_deploy:
- export TRAVIS_TAG="1.3.7.$TRAVIS_BUILD_NUMBER"
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  api_key: b3b7ff74f72ce8f50dab5bc6a36d87cd839c3eeb
  file_glob: true
  file: wheelhouse/*.whl
  skip_cleanup: true
     
